# Generated by Django 2.2.5 on 2019-11-29 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_auto_20191129_1003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='store',
            field=models.CharField(default='', max_length=50),
        ),
    ]
