# Generated by Django 2.2.5 on 2019-11-29 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='store',
            field=models.CharField(default='empty', max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemURL',
            field=models.CharField(max_length=250),
        ),
    ]
